

var questions = [
	"The Milky way is a",
	"The oldest stars in the Milky Way are about ______ years old.",
	"There are more high-mass stars in the Milky Way than low-mass stars.",
	"Population II stars are older than population I stars.",
	"Population I stars _____ than population II stars",
	"Interstellar dust tends to preferentially scatter",
	"Which population of stars has more heavy elements in them?",
	"Shapley used observations of these objects to discover that we are not in the center of the Milky Way",
	"The three main categories of galaxies are:",
	"Hubble discovered that the farther a galaxy is from us,",
	"If Hubble's constant is known, astronomers can use a galaxy's recession velocity to measures its ______ using Hubble's law",
	"Which type of galaxy has a higher percentage of Population I stars?",
	"Which type of galaxy has the least amount of gas?",
	"In general, it is not possible for galaxies to change their type (e.g. Spirals change into Ellipticals).",
	"Spiral galaxies are more likely to be found in",
	"Which type of active galaxy is found at the highest redshift (the most distant)",
	"To explain the speeds of galaxies as they move within a cluster of galaxies, the cluster must be filled with",
	"Distant (and hence younger) clusters appear to have a ______ distribution of galaxies compared to local (older and more evolved) clusters",
	"Gravitational lensing is the",
	"What is the primary cause of the small-scale fluctuations in the Cosmic Microwave Background?",
	"According to modern cosmology, what is the approximate age of the Universe?",
	"The maximum distance that we can in principle see due to the finite age of the Universe and the finite speed of light is called our",
	"The wavelength of light traveling through space as the Universe expands", 
	"In the early Universe, which happened first?",
	"Astronomers have measured the curvature of the Universe to be",
	"The sum of the interior angles of a triangle in a closed (positive curvature) space adds up to", 
	"What is the 'Flatness Problem' that the inflationary model solves?",
	"What is the 'Horizon Problem' that the inflationary model solves?",
	"What is Dark Energy?",
	"Dark energy make up roughly what percentage of the mass (energy) content of the Universe?",
	"A clock near a black-hole will run ______ relative to someone farther away",
	"Edwin Hubble was able to determine the luminosity of Cepheid variables in nearby galaxies because of the",
	"Population I stars are mostly found in the Milky Way's ______",
	"Elliptical galaxies have less Population I stars than spiral galaxies",
	"Hubble's Law states that the closer a galaxy is to us, the ______",
	"The hot intergalactic gas found in galaxy clusters is trapped there by",
	"The cosmic microwave background is old light emitted",
	"The curvature of the surface of a sphere is",
	"Carbon is a good basis for life because it",
	"The transit method for detecting extrasolar planets requires that the planet",
	"Which of the following is not a term in the Drake equation?",
	"Radio waves might be a popular method of communication by intelligent life because",
	"Neither Newton's nor Einstein's models of the universe would work because neither",
	"Which of the following are evidence for the Big Bang Model?",
	"What is significant about an expansion velocity that is proportional to distance?",
	"If the universe is 13.8 billion years old, can any object we see be more than 13.8 billion light years away?",
	"Which of the following best expresses our most accurate modern view of what gravity is?",
	"The cosmic microwave background originated at about 3000 K because that is the temperature",
	"One limitation in studying cosmology is that we",
	"Which of the following is NOT evidence for dark matter?",
	"Which of the following is evidence for dark energy?",
	"Which of the following would make the poorest 'dark matter'?",
	"Which describes the expansion of our universe after inflation?",
	"Which analogy better suits orbital speeds in a typical galaxy?",
	"Which best describes the spatial geometry of the universe?",
	"When galaxy clusters collide,",
	"An alternative to dark matter that might provide a solution but so far has not been a preferred approach is",
	"Which if the best thing to look for to find Earthlike planets?",
	"Which of these would be the best evidence for life on a planet?",
	"What life requirement on the surface of a planet is most rare?",
	"The common type of planet we find around other stars that we did not expect to exist out there is",
	"Mars has attracted recent interest because we have inferred",
	"The idea that the Earth could be very special because we are here is called the",
	"What role do high-mass stars play in the processes that led to life on Earth?",
	"What role do low-mass stars play in the processes that lead to life on planets like the Earth?",
	"Which of these are true about the matter in the universe:",
	"Which of the following is NOT a reason why we need dark matter to explain what we see:",
	"Which of the following are difficult to explain without a rapid 'inflation' very early in the universal expansion:",
	"Which is the greatest uncertainty for contacting technologically advanced aliens?",
	"Why is it thought Mars might have had life in the past?",
	"The anthropic principle asserts that",
	"Why is carbon thought to be crucial for life?",
	"The most distant galaxies appear redder than we would otherwise expect for reasons related to how we could",
	"Quasars could be considered the dinosaurs of the cosmos because",
	"Which of the following galactic regions is least likely to be forming stars now?",
	"When two galaxies collide",
	"Which of the following is NOT a reason to favor the model that the universe expanded from a hot dense state to its current state?",
	"Quasars give us information about what is between us and them via",
	'Which of the following is NOT something that an early era of "inflation" is required to explain:',
	"Which type of galaxy is least likely to contain O stars?",
	"What is the approximate distance to the nearest galaxies beyond our own?",
	"Who was most responsible for our discovering that our galaxy was not alone in the universe?",
	"What is the most convincing argument that most of the matter in the universe does not emit light?",
	'The Hubble constant is called a "constant" because',
	'Which of the following is NOT evidence that we should put "dark energy" into empty space in our best cosmological models?',
	"If I see two star clusters in our galaxy, and one has no stars more massive than 20 solar masses, while the other has stars with masses all the way up to 40 solar masses, then I conclude",
	"Which of the following is the aspect of our models that say alien astronomers 10 billion light years away from us right now see a similar universe that we do?",
	"The gas and stars in most spiral galaxies move at speeds that",
	'What is the meaning of a "standard candle"?',
	'Why do globular clusters not contain white dwarfs with a mass smaller than about half a solar mass?',
	'Why did the Big Bang not create elements heavier than hydrogen (H) and helium (He)?',
	'If the frequency shifts we see when we look at distant galaxies had the same strength but opposite sign, so were blueshifts instead of redshifts, we would conclude',
	'Which of the following currently has an explanation in modern science?',
	'The stars that are most responsible for ionizing the hydrogen gas in between the stars are found in what quadrant of the Hertzsprung-Russell diagram?',
	'Which of the following does not receive its energy from the same fundamental process as the other three?',
	'A galaxy that has has stars orbiting in all different directions will',
	'Which of these is a scientific truth about our best cosmology model?'
];



var choices = [
	["Elliptical galaxy", "Spiral galaxy", "globular cluster", "nearby galaxy", "Irregular galaxy"],  
	["4 million", "4 billion", "13 million", "13 billion", "13 trillion"],
	["True", "False"],
	["True", "False"],
	["have less heavy elements", "are older", "are hotter (bluer)", "all of the above", "none of the above"],
	["long wavelength light", "short wavelength light", "it scatters all light by the same amount"],
	["Population I", "Population II", "Population III", "They have the same amount"],
	["White dwarf stars", "Spiral arms in the disk", "Globular clusters in the halo", "Open clusters in the disk", "Red giants in the bulge"],
	["spiral, elliptical, barred spiral", "spiral, irregular, barred spiral", "spiral, elliptical, irregular", "irregular, barred elliptical, spiral", "elliptical, dwarf irregular, barred spiral"],
	["the slower it is moving away from us", "the more likely it is to be moving toward us", "the faster it is moving toward us", "the faster it is moving away from us", "the more likely it is to be an elliptical galaxy"],
	["distance", "diameter", "luminosity", "age", "class"],
	["Spirals", "Ellipticals", "They have the same amount on average"],
	["Spirals", "Ellipticals", "They have the same amount on average"],
	["True", "False"],
	["the inner parts of galaxy clusters", "the outer parts of galaxy clusters"],
	["Seyfert", "Radio", "Quasars"],
	["dark energy", "dark matter", "dust", "anti-matter", "quark-gluon plasma"],
	["smoother and more spherical", "rougher and more irregular", "similar"],
	["ripples in space-time caused by binary neutron stars", "the bending of light as it passes through the space-time of massive objects", "the warping of a galaxy's image as the force of gravity warps a telescope's lens"],
	["Instrumental error", "Nearby galaxies blocking the light", "The accelerated expansion of the Universe", "Dark matter clumps at the time of last scattering", "Black holes formed during the Dark Ages"],
	["Less than 7000 years", "65 million years", "4.6 billion years", "13.7 billion years", "15 trillion years"],
	["Event horizon", "Cosmic horizon", "Dark Matter", "Schwartzschild radius", "Oort cloud"],
	["gets shorter", "gets longer", "is unchanged"],
	["Helium forms", "Protons and Neutrons form", "The last scattering epoch (atoms form)", "Inflation", "The first stars form"],
	["Positive (closed)", "Negative (open)", "Flat (ordinary geometry)"],
	["exactly 180 degrees", "more than 180 degrees", "less than 180 degrees", "more than 360 degrees", "exactly 360 degrees"],
	["The Universe should only have 2 dimensions, but appears to have 3", "The Universe should have a Flat geometry, but instead has negative curvature", "The Universe should have negative curvature, but it instead is positive", "The Universe has Flat geometry, which is highly unstable", "Planets like Earth should be flat, but are instead spherical"],
	["The Universe should only have 2 dimensions, but it appears to have 3", "The temperature of the Universe is too smooth, even parts outside of each others horizon", "The Cosmic Horizon should be shrinking, but instead it is getting larger", "The Universe has Flat geometry, which is highly unstable", "We should be able to see beyond our horizon, but we can't"],
	["The mysterious particles that cause stars to deviate from Keplerian orbits within galaxies", "The mysterious force causing the expansion of the Universe to accelerate", "The energy used to keep a black hole from exploding", "The energy needed to create a black hole"],
	["0.005%", "0.5%", "4%", "23%", "72%"],
	["faster", "slower", "the same rate"],
	["mass-luminosity relationship", "distance-luminosity relationship", "color-luminosity relationship", "period-luminosity relationship", "he was not able to determine the luminosity"],
	["halo", "globular clusters", "disk", "bulge", "none of the above"],
	["True", "False"],
	["slower it moves away from us", "faster it moves away from us", "harder it is to identify", "the older it is", "more likely it is to support intelligent life"],
	["Dark Energy", "Dark Matter", "magnetic fields", "elliptical galaxies", "inflation"],
	["duration inflation", "during the 'dark ages'", "during the epoch of last scattering (or 'recombination')", "by the first stars that formed after the dark ages", "by the first galaxies that formed after the dark ages"],
	["positive", "negative", "flat"],
	["can bond with four other atoms, allowing for complex molecules to form", "is plentiful in the Universe", "all of the above"],
	["pass in front of the star", "is large enough to wiggle the star back and forth", "be brighter than the star", "be large enough to fully eclipse the star", "have no significant moons"],
	["the fraction of stars that have planets", "the fraction of planets that are Earth-like", "the lifetime of a technologically advanced civilization", "the distance radio waves can travel in one year", "the fraction of planets with life that evolve intelligent species"],
	["it travels faster than other forms of light", "it travels through gas and dust without being scattered or absorbed (as much)", "its short wavelength allows it to carry complicated messages"],
	["could have included gravity", "would have satisfied their own equations", "could have involved a balance", "would have been stable"],
	["cosmic microwave background radiation", "hydrogen and helium content of the universe", "Hubble's law"],
	["every point appears to be at the center", "some places started expanding before others", "it means everything is expanding on all scales", "all light arrives with the same redshift"],
	["No, that's as far as time allowed", "No, light would be absorbed any farther", "Yes, the age doesn't apply to light", "Yes, if it moved away after emitting"],
	["a force that causes objects to accelerate", "a tendency to go to the center of the universe", "an explosion that carries matter outward", "a dynamical effect on space and time"],
	["of microwave light", "when the universe became transparent", "of the initial Big Bang", "the universe has always been"],
	["cannot see the past so we only learn about now", "cannot see the past but we can still guess", "can only see the past of faraway places", "can only see the past of our own galaxy"],
	["dark lanes visible along the spiral arms of some galaxies", "most stars in our galaxy move at about the same speed", "the Bullet Cluster shows strange gravitational lensing", "the need to make the universe spatially flat"],
	["the existence of super-bright emission from quasars", "the redshifts of type Ia supernovae indicate acceleration", "a cosmological constant is needed to make the universe static", "the cosmological principle requires it"],
	["neutrons", "neutrinos", "WIMPs", "electrons"],
	["always accelerating", "always decelerating", "at first decelerating, later accelerating", "at first accelerating, later decelerating"],
	["runners on a track", "planets in our solar system", "spots on a spinning frisbee", "expanding bread"],
	["general relativity allows space to be flat, but it is curved", "general relativity allows space to be curved, but it is flat", "general relativity says space must be flat, and it is", "general relativity says space must be curved, and it is"],
	["the gas and dark matter also collide", "only the dark matter collides, the gas passes through", "only the gas collides, the dark matter passes through", "neither the gas nor the dark matter collide"],
	["include a cosmological constant", "accept the cosmological principle", "allow the universe to be in a steady-state expansion", "change the law of gravity"],
	["motions in the stars they orbit", "changes in brightness in stars they move in front of", "infrared light emitted by the planet", "radio signals coming from advanced civilizations"],
	["oxygen in the atmosphere", "carbon in the surface environment", "a rocky mantle", "internal heat being generated by the planet"],
	["a moderate temperature", "an energy source", "carbon dioxide", "liquid water"],
	["rocky planets the size of Earth", "rocky planets much larger than Earth", "gas planets the size of Earth", "gas planets much larger than Earth"],
	["it must have once had microbial life", "it has canals that indicate intelligent life", "it undergoes seasonal changes in its vegetation", "it had liquid water on its surface in the past"],
	["anthropic principle", "cosmological principle", "Copernican principle", "equivalence principle"],
	["They provide a lot of warmth which helps give life an energy source.",
"They are largely responsible for fusing the elements needed for life.", "They provide a strong gravity which helps pull planets together for life to form on.", "They are the only type of star that ever goes supernova"],
	[	"They have long and stable main-sequence lifetimes, providing the time that life needs to develop.", "They are largely responsible for synthesizing the heavier elements needed for life.", "They produce a lot of ultraviolet light which breaks up carbon dioxide and puts oxygen in the atmosophere", "They go supernova, which spreads elements like carbon and oxygen all over the place."],
	["It is the critical amount to make the expansion slow down until it is very slow in the distant future", "The main component we know about is hydrogren, but most of the matter is something we have not yet identified", "Most the matter everywhere was created in stars, only a little came from the Big Bang", "All of the above"],
	["We see dark regions where the light is being blocked by some unknown material", "We see brightness features that appear to be 'lensed' by the gravity of some unknown foreground material", "We see unexpectedly high velocities in stars and gas in the outer regions of our own galaxy", "We see unexpectedly high velocities of galaxies in the outer regions of galaxy clusters"],
	["The fact that space on the largest scales is still extremely flat", "The fact that the cosmic microwave background is at very nearly the same temperature in all directions", "The reason there are tiny variations in the brightness of the cosmic microwave background"],
	["the number of stars in the galaxy", "the fraction of stars with habitable planets", "the likelihood for life on a planet to become technologically advanced", "the length of time that an advanced species can avoid extinction"],
	["it used to be closer to the Sun where it would be warmer", "it used to have more of an atmosphere than it has now", "it used to have an intelligent species that built canals", "life on Earth probably came from there"],
	["we cannot assume the Earth and Sun are typical", "planets will tend to foster life if it is at all possible", "it is unlikely that intelligent life exists anywhere else in our galaxy", "the laws of physics apply in all reference frames"],
	["carbon makes many types of bonds with other atoms", "carbon is the most common of the heavier elements", "carbon can only be created in the cores of stars", "carbon is important for the greenhouse effect"],
	[	"detect binary stars by looking at shifts in their spectral lines",
		"see red light coming through a lot of air during a sunset",
		"tell we are seeing the red planet Mars rather than Jupiter",
		"tell not to touch a hot coal by the color of its glow"],
	["they were so huge they emit over the volume of a whole galaxy",
		"they only shined while their supermassive black holes were still forming",
		'we cannot directly see them, we infer their existence indirectly via "fossils"',
		"their gravity was so strong they swallowed up all the galaxies around them"],
	[	"galactic core",
		"spiral arms",
		"halo",
		"dust lanes"],
	[	"many binary star systems are created", 
		"stars burn longer due to newly acquired gas", 
		"stars often collide into other stars",
		"new regions of star formation are created"],
	[	"the observation that the universe is spatially flat",
		"the ratio of hydrogen to helium",
		"the detection of a cosmic microwave background",
		"the Hubble law"],
	[	"many spikes in the quasar spectrum called Lyman alpha emission lines",
		"gravitational bending of the quasar light that distorts the quasar image",
		"quasar light is redshifted by intervening dust",
		"quasar illuminates the rotation curves of intervening galaxies"],
	[	"why the cosmic microwave background is the same temperature in all directions",
		"why the universe has much more matter than antimatter",
		"why the universe is expanding in the first place",
		"why the universe is spatially flat"],
	[	"elliptical galaxies",
		"spiral galaxies",
		"irregular galaxies",
		"all galaxies have many O stars"],
	[	"one light year",
		"one thousand light years",
		"one million light years",
		"one billion light years"],
	[	"Hubble",
		"Einstein",
		"Newton",
		"Galileo"],
	[	"most of the Earth's gravity comes from 'dark matter'",
		'galaxies show evidence of extra strong gravitational influences',
		'dark regions are easily seen in many galaxies',
		'the very fact that the universe is expanding requires it to be there'],
	[	"any astronomer anywhere and at any age of the universe gets that same value",
		"any astronomer anywhere in the universe at the present age gets that value",
		"astronomers on Earth will always get that same value for billions of years",
		"it really only applies for us on Earth right now, nowhere else"],
	[	"we need to fix the current expansion without changing the early expansion",
		"we need it to understand why the expansion of the universe is accelerating",
		"we need it to understand how the universe can be found to be spatially flat",
		"we need it to explain the rotation curves of spiral galaxies"],
	[	"the cluster with 40 solar-mass stars is older",
		"the cluster with 40 solar-mass stars is younger",
		"the two clusters formed in different regions where the density was quite different",
		"the two clusters formed in different regions with a different fraction of hydrogen"],
	[	"the cosmological principle",
		"the cosmological constant",
		"the principle of relativity",
		"the Pauli exclusion principle"],
	[	"increase as you go farther from the center, like a merry-go-round",
		"stay about the same, like runners on a many-laned track",
		"decrease as you go farther from the center, to obey Kepler's law",
		"decrease as you go farther from the center, to all have the same angular momentum"],
	[	"it is a way to infer distance from apparent brightness",
		"it is a way to infer the apparent brightness from the luminosity",
		"it is a way to infer distance from the observed redshift",
		"it is a way to infer the apparent brightess from the redshift"],
	[	"globular clusters fly apart before such stars have time to form",
		"no galaxy is old enough to contain such clusters",
		"globular clusters are generally too old to contain such stars",
		"low-mass white dwarfs are more often found in spiral arms"],
	[	'the temperature was never high enough to create anything else',
		'the nuclei that can be created by colliding H and He two at a time are unstable',
		'the lack of heavier elements cannot be explained in the Big Bang model',
		'it did create them, but stars broke them all down to H and He'],
	['the universe would change dramatically in the next 14 billion years',
		'there would need to be even more dark matter than we currently need to explain things',
		'the universe must contain almost no material that could affect light in transit to us',
		'more distant galaxies must have more young stars rather than more old ones'],
	['how the universe originated',
		'why it is rare to find free neutrons floating around in space',
		'what are the particles that make up dark matter',
		'what is the nature of empty space such that it should contain dark energy'],
	['upper left because they are hot and bright',
		'upper right because they are the largest',
		'lower left because they are the hottest',
		'lower right because they are the most numerous'],
	['a landslide',
		'a type Ia supernova',
		'a core-collapse supernova',
		'a gas cloud that is just starting to contract into a star'],
	['be elliptical',
		'be spiral',
		'have an unusually bright central region',
		'have a large redshift'],
	['it has been demonstrated to be correct',
		'it will continue to be subjected to new tests and may change',
		'its reliance on dark matter and dark energy shows it must be wrong',
		'we have returned to the thinking of the ancient Greeks'] 
];

var answers2questions = [
	["Spiral galaxy"],
	["13 billion"],
	["False"],
	["True"],
	["are hotter (bluer)"],
	["short wavelength light"],
	["Population I"],
	["Globular clusters in the halo"],
	["spiral, elliptical, irregular"],
	["the faster it is moving away from us"],
	["distance"],
	["Spirals"],
	["Ellipticals"],
	["False"],
	["the outer parts of galaxy clusters"],
	["Quasars"],
	["dark matter"],
	["rougher and more irregular"],
	["the bending of light as it passes through the space-time of massive objects"],
	["Dark matter clumps at the time of last scattering"],
	["13.7 billion years"],
	["Cosmic horizon"],
	["gets longer"],
	["Inflation"],
	["Flat (ordinary geometry)"],
	["more than 180 degrees"],
	["The Universe has Flat geometry, which is highly unstable"],
	["The temperature of the Universe is too smooth, even parts outside of each others horizon"],
	["The mysterious force causing the expansion of the Universe to accelerate"],
	["72%"],
	["slower"],
	["period-luminosity relationship"],
	["disk"],
	["True"],
	["slower it moves away from us"],
	["Dark Matter"],
	["during the epoch of last scattering (or 'recombination')"],
	["positive"],
	["all of the above"],
	["pass in front of the star"],
	["the distance radio waves can travel in one year"],
	["it travels through gas and dust without being scattered or absorbed (as much)"],
	["would have been stable"],
	["cosmic microwave background radiation", "hydrogen and helium content of the universe", "Hubble's law"],
	["every point appears to be at the center"],
	["Yes, if it moved away after emitting"],
	["a dynamical effect on space and time"],
	["when the universe became transparent"],
	["can only see the past of faraway places"],
	["dark lanes visible along the spiral arms of some galaxies"],
	["the redshifts of type Ia supernovae indicate acceleration"],
	["electrons"],
	["at first decelerating, later accelerating"],
	["runners on a track"],
	["general relativity allows space to be curved, but it is flat"],
	["the gas and dark matter also collide"],
	["change the law of gravity"],
	["changes in brightness in stars they move in front of"],
	["oxygen in the atmosphere"],
	["liquid water"],
	["rocky planets much larger than Earth"],
	["it had liquid water on its surface in the past"],
	["anthropic principle"],
	["They are largely responsible for fusing the elements needed for life."],
	["They are largely responsible for synthesizing the heavier elements needed for life."],
	["The main component we know about is hydrogren, but most of the matter is something we have not yet identified"],
	["We see dark regions where the light is being blocked by some unknown material"],
	["The fact that space on the largest scales is still extremely flat", "The fact that the cosmic microwave background is at very nearly the same temperature in all directions", "The reason there are tiny variations in the brightness of the cosmic microwave background"],
	["the length of time that an advanced species can avoid extinction"],
	["it used to have more of an atmosphere than it has now"],
	["we cannot assume the Earth and Sun are typical"],
	["carbon makes many types of bonds with other atoms"],
	["detect binary stars by looking at shifts in their spectral lines"],
	["they only shined while their supermassive black holes were still forming"],
	["halo"],
	["new regions of star formation are created"],
	["the observation that the universe is spatially flat"],
	["gravitational bending of the quasar light that distorts the quasar image"],
	["why the universe is expanding in the first place"],
	["elliptical galaxies"],
	["one million light years"],
	["Hubble"],
	['galaxies show evidence of extra strong gravitational influences'],
	["any astronomer anywhere in the universe at the present age gets that value"],
	["we need it to explain the rotation curves of spiral galaxies"],
	["the cluster with 40 solar-mass stars is younger"],
	["the cosmological principle"],
	["stay about the same, like runners on a many-laned track"],
	["it is a way to infer distance from apparent brightness"],
	["no galaxy is old enough to contain such clusters"],
	['the nuclei that can be created by colliding H and He two at a time are unstable'],
	['the universe would change dramatically in the next 14 billion years'],
	['why it is rare to find free neutrons floating around in space'],
	['upper left because they are hot and bright'],
	['a type Ia supernova'],
	['be elliptical'],
	['it will continue to be subjected to new tests and may change']
];

var n = 0;
var nMax = questions.length;

function newQuestion() {
	var questionHTML = document.getElementById("question");
	var choicesHTML = document.getElementById("choices");

	var options = "";


	for (i=0; i<choices[n].length; i++) 
	{
		var answer=false;

		for (j=0; j<answers2questions[n].length; j++) 
		{
			if(choices[n][i] === answers2questions[n][j]) 
			{
				answer = true;
			}		
		}

		if(answer) 
		{
			options += "<p class='answer'>" + choices[n][i] + "</p>";
		}
		else 
		{
			options += "<p>" + choices[n][i] + "</p>";
		}
	}

	questionHTML.innerHTML = "<p>" + questions[n] + "</p>";
	choicesHTML.innerHTML = options;

	n = n + 1;
	if (n === nMax) {
		n = 0;
	}
};

function showAnswer() {
	var answerHTML = document.getElementsByClassName("answer");
	for (i=0; i<answerHTML.length; i++)
	{
		answerHTML[i].classList.add("correct");
	}
};

function goBack() {
	if (n < 2) {
		n = nMax - (2 - n);
	} else {
		n = n - 2;
	}
	newQuestion();
};

window.onload = function() {
	newQuestion();
};

